/*
ESTE CÓDIGO SQL RECUPERA LOS NOMBRES Y CORREOS ELECTRÓNICOS DE TODOS LOS CLIENTES, ORDENÁNDOLOS EN ORDEN ALFABÉTICO INVERSO POR APELLIDO Y NOMBRE. 
*/
SELECT 
	first_name,
	last_name,
	email
FROM 
	customer
ORDER BY 
	last_name DESC, 
	first_name DESC