/*	
ESTE CÓDIGO SQL RECUPERA TODOS LOS NOMBRES DE DISTRITOS DISTINTOS REGISTRADOS EN LA TABLA "ADDRESS".
*/
SELECT DISTINCT 
	district
FROM 
	address
/*
ESTE CÓDIGO SQL RECUPERA LA FECHA MÁS RECIENTE EN LA QUE SE REALIZÓ UN ARRENDAMIENTO, ORDENANDO LAS FECHAS DE MANERA DESCENDENTE Y LIMITANDO EL RESULTADO A LA PRIMERA
FILA.
*/
SELECT
	rental_date
FROM
	rental
ORDER BY 
	rental_date DESC
LIMIT 
	1
/*
ESTE CÓDIGO SQL CUENTA EL NÚMERO TOTAL DE PELÍCULAS REGISTRADAS EN LA TABLA "FILM".
*/
SELECT 
	COUNT(*)
FROM 
	film
/*
ESTE CÓDIGO SQL CUENTA CUÁNTOS APELLIDOS DISTINTOS EXISTEN ENTRE TODOS LOS CLIENTES REGISTRADOS EN LA TABLA "CUSTOMER".
*/
SELECT 
	COUNT(DISTINCT last_name)
FROM
	customer