/*
ESTE CÓDIGO SQL CUENTA CUÁNTOS PAGOS HAN SIDO REALIZADOS POR EL CLIENTE CON ID 100 EN LA TABLA "PAYMENT".
*/
SELECT 
	COUNT(*)
FROM 
	payment
WHERE 
	customer_id = 100
/*
ESTE CÓDIGO SQL RECUPERA LOS NOMBRES Y APELLIDOS DE TODOS LOS CLIENTES CUYO NOMBRE ES EXACTAMENTE "ERICA".
*/
SELECT
	first_name,
	last_name
FROM
	customer
WHERE 
	first_name = 'ERICA'