/*
ESTE CÓDIGO SQL CUENTA CUÁNTOS ARRENDAMIENTOS AÚN NO HAN SIDO DEVUELTOS.
*/
SELECT 
	COUNT(*)
FROM 
	rental
WHERE 
	return_date IS NULL
/*
ESTE CÓDIGO SQL RECUPERA LOS IDENTIFICADORES DE PAGO Y SUS MONTOS PARA AQUELLAS TRANSACCIONES CUYO VALOR SEA MENOR O IGUAL A 2 DÓLARES.
*/
SELECT 
	payment_id,
	amount
FROM 
	payment
WHERE 
	amount <= 2