/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS PAGOS REALIZADOS POR LOS CLIENTES CON ID 322, 346 Y 354, FILTRANDO AQUELLOS CUYO MONTO SEA MENOR A 2 DÓLARES O MAYOR A 10 DÓLARES. LOS
RESULTADOS SE ORDENAN POR ID DE CLIENTE EN ORDEN ASCENDENTE Y POR MONTO DE PAGO EN ORDEN DESCENDENTE.
*/
SELECT 
	*
FROM 
	payment
WHERE 
	(customer_id = 322 OR customer_id = 346 OR customer_id = 354)
	AND (amount < 2 OR amount > 10)
ORDER BY 
	customer_id ASC,
	amount DESC