/*
ESTE CÓDIGO SQL CUENTA CUÁNTAS PELÍCULAS EN LA TABLA "FILM" CONTIENEN LA PALABRA "DOCUMENTARY" EN SU DESCRIPCIÓN.
*/
SELECT 
	COUNT(*)
FROM 
	film
WHERE 
	description ILIKE '%Documentary%'
/*
ESTE CÓDIGO SQL CUENTA CUÁNTOS CLIENTES TIENEN UN NOMBRE DE EXACTAMENTE TRES LETRAS Y UN APELLIDO QUE TERMINA EN "X" O "Y".
*/
SELECT 
	COUNT(*)
FROM 
	customer
WHERE 
	(first_name ILIKE '___')
	AND (last_name ILIKE '%X' OR last_name ILIKE '%Y')