/*
ESTE CÓDIGO SQL CUENTA CUÁNTAS PELÍCULAS EN LA TABLA "FILM" CONTIENEN LA PALABRA "SAGA" EN SU DESCRIPCIÓN Y CUYO TÍTULO COMIENZA CON LA LETRA "A" O TERMINA CON LA LETRA
"R".
*/
SELECT 
	COUNT(*) AS no_of_movies
FROM 
	film
WHERE 
	(description ILIKE '%SAGA%')
	AND (title ILIKE 'A%' OR title ILIKE '%R')
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS CLIENTES CUYO NOMBRE CONTIENE LA SECUENCIA "ER" Y ADEMÁS TIENE UNA SEGUNDA LETRA "A", Y LOS RESULTADOS SE ORDENAN POR APELLIDO EN ORDEN
DESCENDENTE.
*/
SELECT 
	*
FROM 
	customer
WHERE 
	(first_name ILIKE '%ER%')
	AND (first_name ILIKE '_A%')
ORDER BY 
	last_name DESC
/*
ESTE CÓDIGO SQL CUENTA CUÁNTOS PAGOS FUERON REALIZADOS EL DÍA 1 DE MAYO DE 2020, CUYO MONTO FUE IGUAL A 0 O ESTUVO ENTRE 3.99 Y 7.99 DÓLARES.
*/
SELECT 
	COUNT(*)
FROM 
	payment
WHERE 
	(amount = 0 OR amount BETWEEN 3.99 AND 7.99)
	AND (payment_date BETWEEN '2020-05-01' AND '2020-05-01 23:59')