/*
ESTE CÓDIGO SQL OBTIENE ESTADÍSTICAS SOBRE EL COSTO DE REEMPLAZO DE LAS PELÍCULAS EN LA TABLA "FILM", INCLUYENDO EL VALOR MÍNIMO, MÁXIMO, PROMEDIO (REDONDEADO A DOS
DECIMALES) Y LA SUMA TOTAL DE TODOS LOS COSTOS.
*/
SELECT
	MIN(replacement_cost),
	MAX(replacement_cost),
	ROUND(AVG(replacement_cost),2) AS AVG,
	SUM(replacement_cost)
FROM 
	film