/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DE LOS PAGOS REALIZADOS POR CADA EMPLEADO, MOSTRANDO LA SUMA TOTAL Y LA CANTIDAD DE TRANSACCIONES PROCESADAS. LOS RESULTADOS SE AGRUPAN
POR ID DE EMPLEADO Y SE ORDENAN DE MAYOR A MENOR SEGÚN EL MONTO TOTAL COBRADO.
*/
SELECT
	staff_id,
	SUM(amount),
	COUNT(amount)
FROM 
	payment
GROUP BY 
	staff_id
ORDER BY
	SUM(amount) DESC
/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DE LOS PAGOS POSITIVOS REALIZADOS POR CADA EMPLEADO, MOSTRANDO LA SUMA TOTAL Y LA CANTIDAD DE TRANSACCIONES CON MONTO MAYOR A CERO. LOS
RESULTADOS SE AGRUPAN POR ID DE EMPLEADO Y SE ORDENAN DE MAYOR A MENOR SEGÚN EL MONTO TOTAL COBRADO.
*/
SELECT
	staff_id,
	SUM(amount),
	COUNT(amount)
FROM 
	payment
WHERE
	amount > 0
GROUP BY 
	staff_id
ORDER BY
	SUM(amount) DESC