/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DIARIO DE LOS PAGOS REALIZADOS POR CADA EMPLEADO, MOSTRANDO LA FECHA, EL MONTO TOTAL COBRADO Y LA CANTIDAD DE TRANSACCIONES POR DÍA. LOS
RESULTADOS SE AGRUPAN POR ID DE EMPLEADO Y FECHA DE PAGO, Y SE ORDENAN DE MAYOR A MENOR SEGÚN EL MONTO TOTAL COBRADO.
*/
SELECT 
	staff_id,
	DATE(payment_date),
	SUM(amount),
	COUNT(*)
FROM 
	payment
GROUP BY 
	staff_id,
	DATE(payment_date)
ORDER BY
	SUM(amount) DESC
/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DIARIO DE LOS PAGOS POSITIVOS REALIZADOS POR CADA EMPLEADO, MOSTRANDO LA FECHA, EL MONTO TOTAL COBRADO Y LA CANTIDAD DE TRANSACCIONES POR
DÍA. LOS RESULTADOS SE AGRUPAN POR ID DE EMPLEADO Y FECHA DE PAGO, Y SE ORDENAN DE MAYOR A MENOR SEGÚN LA CANTIDAD DE TRANSACCIONES.
*/
SELECT
	staff_id,
	DATE(payment_date),
	SUM(amount),
	COUNT(*)
FROM 
	payment
WHERE
	amount > 0
GROUP BY
	staff_id,
	DATE(payment_date)
ORDER BY
	COUNT(*) DESC