/*
ESTE CÓDIGO SQL GENERA UN REPORTE DE LOS CLIENTES QUE REALIZARON MÁS DE UNA TRANSACCIÓN EN FECHAS ESPECÍFICAS (28, 29 Y 30 DE ABRIL DE 2020). MUESTRA EL ID DEL CLIENTE,
LA FECHA DE PAGO, EL PROMEDIO REDONDEADO DEL MONTO PAGADO Y EL NÚMERO DE TRANSACCIONES. LOS RESULTADOS SE AGRUPAN POR CLIENTE Y FECHA, Y SE ORDENAN DE MAYOR A MENOR SEGÚN
EL PROMEDIO DEL MONTO PAGADO.
*/
SELECT
	customer_id,
	DATE(payment_date),
	ROUND(AVG(amount),2) AS avg_amount,
	COUNT(*)
FROM
	payment
WHERE
	DATE(payment_date) IN ('2020-04-28','2020-04-29','2020-04-30')
GROUP BY
	customer_id,
	DATE(payment_date)
HAVING
	COUNT(*) > 1
ORDER BY
	avg_amount DESC