/*
ESTE CÓDIGO SQL RECUPERA LOS NOMBRES, APELLIDOS Y CORREOS ELECTRÓNICOS DE CLIENTES CUYOS NOMBRES O APELLIDOS TIENEN MÁS DE 10 CARACTERES, CONVIRTIENDO TODOS LOS CAMPOS A
MINÚSCULAS PARA UNIFORMIDAD EN LA PRESENTACIÓN.
*/
SELECT
	LOWER(first_name),
	LOWER(last_name),
	LOWER(email)
FROM
	customer
WHERE 
	(LENGTH(first_name) > 10)
	OR (LENGTH(last_name) > 10)