/*
ESTE CÓDIGO SQL MUESTRA EL CORREO ELECTRÓNICO DE CADA CLIENTE JUNTO CON LOS ÚLTIMOS 5 CARACTERES DE SU DIRECCIÓN DE CORREO, UTILIZANDO LA FUNCIÓN RIGHT PARA EXTRAER ESA
PORCIÓN DEL TEXTO.
*/
SELECT
	email,
	RIGHT(email,5)
FROM
	customer
/*
ESTE CÓDIGO SQL MUESTRA EL CORREO ELECTRÓNICO DE CADA CLIENTE JUNTO CON EL PRIMER CARÁCTER DE LOS ÚLTIMOS 4 CARACTERES DE SU DIRECCIÓN DE CORREO, UTILIZANDO LAS FUNCIONES
RIGHT Y LEFT PARA EXTRAER ESA PORCIÓN ESPECÍFICA DEL TEXTO.
*/
SELECT
	email,
	LEFT(RIGHT(email,4),1)
FROM
	customer