/*
ESTE CÓDIGO SQL GENERA UNA VERSIÓN ANONIMIZADA DEL CORREO ELECTRÓNICO DE CADA CLIENTE, MOSTRANDO SOLO EL PRIMER CARÁCTER, SEGUIDO DE TRES ASTERISCOS Y LOS ÚLTIMOS 19
CARACTERES DEL CORREO ORIGINAL, UTILIZANDO CONCATENACIÓN CON LAS FUNCIONES LEFT Y RIGHT.
*/
SELECT
	LEFT(email,1) || '***' || RIGHT(email,19) AS anonymized_email
FROM
	customer