/*
ESTE CÓDIGO SQL CONCATENA EL APELLIDO DEL CLIENTE CON UNA PARTE DE SU CORREO ELECTRÓNICO, EXTRAÍDA DESDE EL INICIO HASTA ANTES DEL PRIMER PUNTO, SEPARADOS POR UNA COMA.
TAMBIÉN MUESTRA EL APELLIDO POR SEPARADO. UTILIZA LAS FUNCIONES LEFT Y POSITION PARA LOCALIZAR Y EXTRAER LA PORCIÓN DEL CORREO.
*/
SELECT
	last_name || ',' || LEFT(email,POSITION('.' IN email)-1),
	last_name
FROM
	customer