/*
ESTE CÓDIGO SQL CREA UNA VERSIÓN PARCIALMENTE ANONIMIZADA DEL CORREO ELECTRÓNICO DE CADA CLIENTE. MUESTRA EL PRIMER CARÁCTER DEL CORREO, SEGUIDO DE TRES ASTERISCOS, DOS
CARACTERES A PARTIR DEL PRIMER PUNTO EN EL CORREO, OTROS TRES ASTERISCOS Y FINALMENTE TODO LO QUE SIGUE DESPUÉS DEL SÍMBOLO '@'. UTILIZA LAS FUNCIONES LEFT, SUBSTRING Y
POSITION PARA EXTRAER Y CONCATENAR LAS PARTES DEL CORREO.
*/
SELECT
	LEFT(email,1) || '***' || SUBSTRING(email FROM POSITION('.' IN email) FOR 2) || '***' || SUBSTRING(email FROM POSITION('@' IN email))
FROM
	customer
/*
ESTE CÓDIGO SQL GENERA UNA VERSIÓN ANONIMIZADA DEL CORREO ELECTRÓNICO DE CADA CLIENTE, EXTRAYENDO TRES CARACTERES QUE INCLUYEN EL CARÁCTER ANTERIOR AL PRIMER PUNTO Y LOS
DOS SIGUIENTES, ENVUELTOS ENTRE ASTERISCOS, Y AÑADIENDO TODO LO QUE SIGUE DESPUÉS DEL SÍMBOLO '@'. SE UTILIZAN LAS FUNCIONES SUBSTRING Y POSITION PARA LOCALIZAR Y EXTRAER
LAS PARTES DEL CORREO.
*/
SELECT
	'***' || SUBSTRING(email FROM POSITION('.' IN email)-1 FOR 3) || '***' || SUBSTRING(email FROM POSITION('@' IN email))
FROM
	customer