/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DEL MONTO TOTAL PAGADO POR MES, EXTRAÍDO DE LA FECHA DE PAGO DE CADA TRANSACCIÓN. AGRUPA LOS RESULTADOS POR MES Y LOS ORDENA DE MAYOR A
MENOR SEGÚN EL MONTO TOTAL PAGADO EN CADA MES.
*/
SELECT
	EXTRACT(MONTH FROM payment_date) AS month,
	SUM(amount) AS total_payment_amount
FROM
	payment
GROUP BY
	month
ORDER BY
	total_payment_amount DESC
/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DEL MONTO TOTAL PAGADO AGRUPADO POR DÍA DE LA SEMANA, EXTRAÍDO DE LA FECHA DE PAGO DE CADA TRANSACCIÓN. UTILIZA LA FUNCIÓN EXTRACT PARA
OBTENER EL DÍA DE LA SEMANA (DOW), AGRUPA LOS RESULTADOS POR ESE DÍA Y LOS ORDENA DE MAYOR A MENOR SEGÚN EL MONTO TOTAL PAGADO.
*/
SELECT
	EXTRACT(DOW FROM payment_date) AS day_of_week,
	SUM(amount) AS total_payment_amount
FROM
	payment
GROUP BY
	day_of_week
ORDER BY
	total_payment_amount DESC
/*
ESTE CÓDIGO SQL GENERA UN REPORTE DEL MONTO TOTAL PAGADO POR CADA CLIENTE AGRUPADO POR SEMANA DEL AÑO, EXTRAÍDA DE LA FECHA DE PAGO DE CADA TRANSACCIÓN. UTILIZA LA FUNCIÓN
EXTRACT PARA OBTENER LA SEMANA, AGRUPA LOS RESULTADOS POR ID DE CLIENTE Y SEMANA, Y LOS ORDENA DE MAYOR A MENOR SEGÚN EL MONTO TOTAL PAGADO.
*/
SELECT
	customer_id,
	EXTRACT(week FROM payment_date) AS week,
	SUM(amount) AS total_payment_amount
FROM
	payment
GROUP BY
	customer_id,
	week
ORDER BY
	total_payment_amount DESC