/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DEL MONTO TOTAL PAGADO AGRUPADO POR DÍA, FORMATEANDO LA FECHA PARA MOSTRAR EL DÍA DE LA SEMANA, EL DÍA DEL MES Y EL AÑO EN FORMATO
'Dy, DD/MM/YYYY'. UTILIZA LA FUNCIÓN TO_CHAR PARA FORMATEAR LA FECHA Y AGRUPA LOS RESULTADOS POR ESE FORMATO, ORDENÁNDOLOS DE MAYOR A MENOR SEGÚN EL MONTO TOTAL PAGADO.
*/
SELECT
	SUM(amount) AS total_payment,
	TO_CHAR(payment_date,'Dy, DD/MM/YYYY') AS day
FROM
	payment
GROUP BY
	day
ORDER BY
	total_payment DESC
/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DEL MONTO TOTAL PAGADO AGRUPADO POR MES Y AÑO, FORMATEANDO LA FECHA EN EL ESTILO 'Mon, YYYY' PARA MOSTRAR EL MES ABREVIADO Y EL AÑO. 
UTILIZA LA FUNCIÓN TO_CHAR PARA FORMATEAR LA FECHA Y AGRUPA LOS RESULTADOS POR ESE FORMATO, ORDENÁNDOLOS DE MENOR A MAYOR SEGÚN EL MONTO TOTAL PAGADO.
*/
SELECT
	SUM(amount) AS total_payment,
	TO_CHAR(payment_date,'Mon, YYYY') AS mon_year
FROM
	payment
GROUP BY
	mon_year
ORDER BY
	total_payment ASC
/*
ESTE CÓDIGO SQL GENERA UN RESUMEN DEL MONTO TOTAL PAGADO AGRUPADO POR DÍA DE LA SEMANA Y HORA (EN FORMATO DE 12 HORAS CON MINUTOS), UTILIZANDO LA FUNCIÓN TO_CHAR PARA
FORMATEAR LA FECHA Y HORA DE PAGO. LOS RESULTADOS SE ORDENAN DE MAYOR A MENOR SEGÚN EL MONTO TOTAL PAGADO.
*/
SELECT
	SUM(amount) AS total_payment,
	TO_CHAR(payment_date,'Dy, HH:MI') AS day_time
FROM
	payment
GROUP BY
	day_time
ORDER BY
	total_payment DESC