/*
ESTE CÓDIGO SQL CALCULA LA DURACIÓN DEL PERIODO DE RENTA PARA CADA TRANSACCIÓN REALIZADA POR EL CLIENTE CON ID 35, RESTANDO LA FECHA DE INICIO DE LA RENTA DE LA FECHA DE
DEVOLUCIÓN. MUESTRA EL ID DEL CLIENTE Y LA DURACIÓN DE LA RENTA EN DÍAS.
*/
SELECT
	customer_id,
	return_date - rental_date AS rental_duration
FROM
	rental
WHERE
	customer_id = 35
/*
ESTE CÓDIGO SQL CALCULA EL PROMEDIO DE LA DURACIÓN DE LAS RENTAS PARA CADA CLIENTE, RESTANDO LA FECHA DE INICIO DE LA RENTA DE LA FECHA DE DEVOLUCIÓN. AGRUPA LOS
RESULTADOS POR ID DE CLIENTE Y LOS ORDENA DE MAYOR A MENOR SEGÚN LA DURACIÓN PROMEDIO DE LAS RENTAS.
*/
SELECT
	customer_id,
	AVG(return_date - rental_date) AS rental_duration
FROM
	rental
GROUP BY
	customer_id
ORDER BY
	rental_duration DESC