/*
ESTE CÓDIGO SQL CALCULA EL PORCENTAJE QUE REPRESENTA LA TARIFA DE RENTA RESPECTO AL COSTO DE REEMPLAZO PARA CADA PELÍCULA, REDONDEADO A DOS DECIMALES. FILTRA LOS RESULTADOS
PARA MOSTRAR SOLO AQUELLAS PELÍCULAS CUYO PORCENTAJE ES MENOR A 4%, Y LOS ORDENA DE MENOR A MAYOR SEGÚN ESE PORCENTAJE.
*/
SELECT
	film_id,
	ROUND(rental_rate / replacement_cost * 100,2) AS percentage
FROM
	film
WHERE
	ROUND(rental_rate / replacement_cost * 100,2) < 4
ORDER BY
	percentage