/*
ESTE CÓDIGO SQL CLASIFICA LAS PELÍCULAS EN DIFERENTES NIVELES (TIERS) SEGÚN SU CLASIFICACIÓN, DURACIÓN, DESCRIPCIÓN Y TARIFA DE RENTA. UTILIZA UNA EXPRESIÓN CASE PARA
ASIGNAR UNA ETIQUETA A CADA PELÍCULA BASADA EN LAS CONDICIONES DEFINIDAS, COMO CLASIFICACIÓN 'PG' O 'PG-13', DURACIÓN MAYOR A 210 MINUTOS, CONTENIDO DRAMÁTICO Y TARIFA DE
RENTA BAJA. LA CLÁUSULA WHERE FILTRA SOLO AQUELLAS PELÍCULAS QUE CUMPLEN ALGUNA DE LAS CONDICIONES DEFINIDAS EN LA EXPRESIÓN CASE, ASEGURANDO QUE SOLO SE MUESTREN LAS QUE
TIENEN UNA CATEGORÍA ASIGNADA.
*/
SELECT
	title,
	CASE
		WHEN rating IN ('PG', 'PG-13') OR length > 210 THEN 'GREAT RATING OR VERY LONG (TIER 1)'
		WHEN description LIKE '%Drama%' AND length > 90 THEN 'LONG DRAMA (TIER 2)'
		WHEN description LIKE '%Drama%' THEN 'SHORT DRAMA (TIER 3)'
		WHEN rental_rate < 1 THEN 'VERY CHEAP (TIER 4)'
	END AS tier_list
FROM
	film
WHERE
	CASE
		WHEN rating IN ('PG', 'PG-13') OR length > 210 THEN 'GREAT RATING OR VERY LONG (TIER 1)'
		WHEN description LIKE '%Drama%' AND length > 90 THEN 'LONG DRAMA (TIER 2)'
		WHEN description LIKE '%Drama%' THEN 'SHORT DRAMA (TIER 3)'
		WHEN rental_rate < 1 THEN 'VERY CHEAP (TIER 4)'
	END IS NOT NULL