/*
ESTE CÓDIGO SQL CLASIFICA LAS RESERVAS EN TRES CATEGORÍAS DE PRECIO (BAJO, MEDIO Y ALTO) SEGÚN EL MONTO TOTAL DE CADA UNA, UTILIZANDO UNA EXPRESIÓN CASE. CUENTA CUÁNTAS
RESERVAS HAY EN CADA CATEGORÍA Y AGRUPA LOS RESULTADOS POR TIPO DE PRECIO.
*/
SELECT
	COUNT(*),
	CASE
		WHEN total_amount < 20000 THEN 'LOW PRICE TICKET'
		WHEN total_amount <150000 THEN 'MID PRICE TICKET'
		ELSE 'HIGH PRICE TICKET'
	END AS ticket_price
FROM
	bookings
GROUP BY
	ticket_price
/*
ESTE CÓDIGO SQL CLASIFICA LOS VUELOS SEGÚN LA ESTACIÓN DEL AÑO EN LA QUE ESTÁ PROGRAMADA SU SALIDA, UTILIZANDO LA FUNCIÓN EXTRACT PARA OBTENER EL MES Y UNA EXPRESIÓN CASE
PARA ASIGNAR LA ESTACIÓN CORRESPONDIENTE. CUENTA CUÁNTOS VUELOS HAY EN CADA ESTACIÓN Y AGRUPA LOS RESULTADOS POR ESTA CATEGORÍA.
*/
SELECT
	COUNT(*) AS flights,
	CASE
		WHEN EXTRACT(MONTH FROM scheduled_departure) IN (12,1,2) THEN 'WINTER'
		WHEN EXTRACT(MONTH FROM scheduled_departure) <= 5 THEN 'SPRING'
		WHEN EXTRACT(MONTH FROM scheduled_departure) <= 8 THEN 'SUMMER'
		ELSE 'FALL'
	END AS season
FROM
	flights
GROUP BY
	season