/*
ESTE CÓDIGO SQL MUESTRA LA FECHA DE INICIO DE LA RENTA Y LA FECHA DE DEVOLUCIÓN PARA CADA TRANSACCIÓN. SI LA FECHA DE DEVOLUCIÓN ES NULA, SE REEMPLAZA CON EL TEXTO
'NOT RETURNED' UTILIZANDO LA FUNCIÓN COALESCE. ADEMÁS, LA FECHA DE DEVOLUCIÓN SE CONVIERTE A TEXTO CON LA FUNCIÓN CAST PARA UNIFORMIDAD EN LA SALIDA.
*/
SELECT
	rental_date,
	COALESCE(CAST(return_date AS VARCHAR),'NOT RETURNED')
FROM
	rental