/*
ESTE CÓDIGO SQL MUESTRA EL NÚMERO DE VUELO Y UNA VERSIÓN NUMÉRICA DEL MISMO, ELIMINANDO EL PREFIJO 'PG' DE LA CADENA DE TEXTO Y CONVIRTIENDO EL RESULTADO A ENTERO USANDO LAS
FUNCIONES REPLACE Y CAST.
*/
SELECT
	flight_no,
	CAST(REPLACE(flight_no,'PG','') AS INT)
FROM
	flights