/*
ESTE CÓDIGO SQL CUENTA CUÁNTOS REGISTROS EXISTEN EN LA TABLA TICKETS QUE NO TIENEN UN PASE DE ABORDAR ASOCIADO, UTILIZANDO UNA UNIÓN COMPLETA (FULL OUTER JOIN) ENTRE LAS
TABLAS BOARDING_PASSES Y TICKETS. LA CONDICIÓN EN LA CLÁUSULA WHERE FILTRA LOS CASOS EN LOS QUE EL NÚMERO DE TICKET EN LA TABLA BOARDING_PASSES ES NULO, ES DECIR, TICKETS
QUE NO HAN SIDO UTILIZADOS PARA ABORDAR.
*/
SELECT
	COUNT(*)
FROM
	boarding_passes
FULL OUTER JOIN
	tickets
ON
	boarding_passes.ticket_no = tickets.ticket_no
WHERE
	boarding_passes.ticket_no IS NULL