/*
ESTE CÓDIGO SQL GENERA UN REPORTE DE LA CANTIDAD DE PASES DE ABORDAR POR CONDICIÓN DE TARIFA, REALIZANDO UNA UNIÓN ENTRE LAS TABLAS BOARDING_PASSES, FLIGHTS Y SEATS
MEDIANTE LAS CLAVES DE VUELO Y NÚMERO DE ASIENTO. AGRUPA LOS RESULTADOS POR CONDICIÓN DE TARIFA Y LOS ORDENA DE MAYOR A MENOR SEGÚN LA CANTIDAD DE REGISTROS.
*/
SELECT
	fare_conditions AS "FARE CONDITIONS",
	COUNT(*)
FROM
	boarding_passes
INNER JOIN
	flights
ON
	boarding_passes.flight_id = flights.flight_id
INNER JOIN
	seats
ON
	boarding_passes.seat_no = seats.seat_no
	AND flights.aircraft_code = seats.aircraft_code
GROUP BY
	"FARE CONDITIONS"
ORDER BY
	COUNT(*) DESC