/*
ESTE CÓDIGO SQL IDENTIFICA LOS REGISTROS DE AERONAVES QUE NO HAN SIDO ASIGNADOS A NINGÚN VUELO. UTILIZA UNA CONSULTA CON LEFT OUTER JOIN ENTRE LAS TABLAS DE DATOS DE
AERONAVES Y VUELOS, FILTRANDO AQUELLAS AERONAVES CUYO ID DE VUELO ES NULO, ES DECIR, QUE NO TIENEN VUELOS ASOCIADOS.
*/
SELECT
	*
FROM
	aircrafts_data
LEFT OUTER JOIN
	flights
ON
	aircrafts_data.aircraft_code = flights.aircraft_code
WHERE
	flights.flight_id IS NULL
/*
ESTE CÓDIGO SQL MUESTRA LA CANTIDAD DE VECES QUE CADA ASIENTO HA SIDO UTILIZADO EN LOS PASES DE ABORDAR. REALIZA UNA UNIÓN IZQUIERDA ENTRE LAS TABLAS DE ASIENTOS Y PASES
DE ABORDAR, AGRUPANDO POR NÚMERO DE ASIENTO Y ORDENANDO LOS RESULTADOS DE MAYOR A MENOR SEGÚN LA CANTIDAD DE USOS.
*/
SELECT
	seats.seat_no,
	COUNT(*)
FROM
	seats
LEFT OUTER JOIN
	boarding_passes
ON
	seats.seat_no = boarding_passes.seat_no
GROUP BY
	seats.seat_no
ORDER BY
	COUNT(*) DESC
/*
ESTE CÓDIGO SQL ANALIZA LA FRECUENCIA DE USO DE LOS ASIENTOS SEGÚN LA LETRA FINAL DEL NÚMERO DE ASIENTO, QUE GENERALMENTE REPRESENTA LA COLUMNA O POSICIÓN EN LA FILA.
AGRUPA LOS RESULTADOS POR ESA LETRA FINAL Y CUENTA CUÁNTAS VECES HA SIDO UTILIZADA EN LOS PASES DE ABORDAR, ORDENANDO DE MAYOR A MENOR SEGÚN LA CANTIDAD DE USOS.
*/
SELECT
	RIGHT(seats.seat_no,1),
	COUNT(*)
FROM
	seats
LEFT OUTER JOIN
	boarding_passes
ON
	seats.seat_no = boarding_passes.seat_no
GROUP BY
	RIGHT(seats.seat_no,1)
ORDER BY
	COUNT(*) DESC