/*
ESTE CÓDIGO SQL OBTIENE LA INFORMACIÓN DE CLIENTES QUE VIVEN EN EL DISTRITO DE TEXAS. REALIZA UNA UNIÓN IZQUIERDA ENTRE LAS TABLAS DE CLIENTES Y DIRECCIONES PARA MOSTRAR
EL NOMBRE, APELLIDO, TELÉFONO Y DISTRITO DE CADA CLIENTE CUYO DISTRITO SEA EXACTAMENTE 'TEXAS'.
*/
SELECT
	first_name,
	last_name,
	phone,
	district
FROM
	customer
LEFT OUTER JOIN
	address
ON
	customer.address_id = address.address_id
WHERE
	district = 'Texas'
/*
ESTE CÓDIGO SQL IDENTIFICA LAS DIRECCIONES QUE NO ESTÁN ASOCIADAS A NINGÚN CLIENTE. UTILIZA UNA UNIÓN DERECHA ENTRE LAS TABLAS DE CLIENTES Y DIRECCIONES, FILTRANDO
AQUELLAS DIRECCIONES CUYO ID DE CLIENTE ES NULO, ES DECIR, QUE NO TIENEN CLIENTES RELACIONADOS.
*/
SELECT
	address.address_id,
	address
FROM
	customer
RIGHT OUTER JOIN
	address
ON
	customer.address_id = address.address_id
WHERE
	customer_id IS NULL