/*
ESTE CÓDIGO SQL CALCULA EL PROMEDIO DE MONTO PAGADO POR ASIENTO EN LOS VUELOS, REDONDEADO A DOS DECIMALES. REALIZA UNA UNIÓN INTERNA ENTRE LAS TABLAS DE PASES DE ABORDAR Y
VUELOS DE BOLETOS, AGRUPANDO POR NÚMERO DE ASIENTO Y ORDENANDO LOS RESULTADOS DE MAYOR A MENOR SEGÚN EL PROMEDIO DEL MONTO PAGADO.
*/
SELECT
	seat_no,
	ROUND(AVG(amount),2)
FROM
	boarding_passes
INNER JOIN
	ticket_flights
ON
	boarding_passes.ticket_no = ticket_flights.ticket_no
	AND boarding_passes.flight_id = ticket_flights.flight_id
GROUP BY
	seat_no
ORDER BY
	ROUND(AVG(amount),2) DESC