/*
ESTE CÓDIGO SQL OBTIENE EL NOMBRE DE LOS PASAJEROS JUNTO CON LA SUMA TOTAL DE LOS MONTOS PAGADOS POR SUS BOLETOS. REALIZA UNA UNIÓN INTERNA ENTRE LAS TABLAS DE BOLETOS Y
RESERVAS, AGRUPA LOS RESULTADOS POR NOMBRE DEL PASAJERO Y ORDENA LA SUMA TOTAL DE LOS MONTOS EN ORDEN DESCENDENTE PARA MOSTRAR A LOS PASAJEROS QUE HAN GASTADO MÁS.
*/
SELECT
	passenger_name,
	SUM(total_amount)
FROM
	tickets
INNER JOIN
	bookings
ON
	tickets.book_ref = bookings.book_ref
GROUP BY
	passenger_name
ORDER BY
	SUM(total_amount) DESC
/*
ESTE CÓDIGO SQL RECUPERA LA CANTIDAD DE VUELOS ASOCIADOS A UN PASAJERO ESPECÍFICO LLAMADO 'ALEKSANDR IVANOV', AGRUPADOS POR LAS CONDICIONES DE TARIFA. REALIZA UNA UNIÓN
INTERNA ENTRE LAS TABLAS DE BOLETOS Y VUELOS DE BOLETOS, FILTRA POR EL NOMBRE DEL PASAJERO Y AGRUPA LOS RESULTADOS PARA MOSTRAR CUÁNTOS VUELOS HA TENIDO BAJO CADA TIPO DE
TARIFA.
*/
SELECT
	passenger_name
	fare_conditions,
	COUNT(*)
FROM
	tickets
INNER JOIN
	ticket_flights
ON
	tickets.ticket_no = ticket_flights.ticket_no
	AND passenger_name = 'ALEKSANDR IVANOV'
GROUP BY
	passenger_name,
	fare_conditions