/*
ESTE CÓDIGO SQL RECUPERA TODAS LAS PELÍCULAS CUYA DURACIÓN ES MAYOR AL PROMEDIO DE DURACIÓN DE TODAS LAS PELÍCULAS EN LA TABLA 'FILM'. UTILIZA UNA SUBCONSULTA PARA
CALCULAR EL PROMEDIO Y LO COMPARA CON LA COLUMNA 'LENGTH' EN LA CONDICIÓN DEL WHERE.
*/
SELECT 
	*
FROM
	film
WHERE
	length > (SELECT
			  	  AVG(length)
			  FROM
				  film)
/*
ESTE CÓDIGO SQL RECUPERA TODAS LAS PELÍCULAS QUE ESTÁN DISPONIBLES EN LA TIENDA CON ID 2 Y QUE TIENEN MÁS DE 3 COPIAS EN INVENTARIO. UTILIZA UNA SUBCONSULTA PARA
IDENTIFICAR LOS 'FILM_ID' QUE CUMPLEN CON ESTA CONDICIÓN, AGRUPANDO POR ID DE PELÍCULA Y APLICANDO LA CLÁUSULA HAVING PARA FILTRAR AQUELLAS CON MÁS DE TRES REGISTROS.
*/
SELECT
	*
FROM
	film
WHERE
	film_id IN (SELECT
					film_id
				FROM
					inventory
				WHERE
					store_id = 2
				GROUP BY
					film_id
				HAVING
					COUNT(*) > 3)