/*
ESTE CÓDIGO SQL OBTIENE LOS NOMBRES Y APELLIDOS DE LOS CLIENTES QUE REALIZARON UN PAGO EXACTAMENTE EL DÍA '2020-01-25'. UTILIZA UNA SUBCONSULTA PARA FILTRAR LOS
'CUSTOMER_ID' DE LA TABLA DE PAGOS CUYA FECHA DE PAGO COINCIDE CON LA FECHA ESPECIFICADA, Y LUEGO RECUPERA LOS DATOS CORRESPONDIENTES DE LA TABLA DE CLIENTES.
*/
SELECT
	first_name,
	last_name
FROM
	customer
WHERE
	customer_id IN (SELECT
						customer_id
					FROM
						payment
					WHERE
						DATE(payment_date) = '2020-01-25')
/*
ESTE CÓDIGO SQL OBTIENE LOS NOMBRES Y CORREOS ELECTRÓNICOS DE LOS CLIENTES QUE HAN REALIZADO PAGOS CUYO MONTO TOTAL SUPERA LOS 30. UTILIZA UNA SUBCONSULTA QUE AGRUPA LOS
PAGOS POR 'CUSTOMER_ID' Y APLICA LA FUNCIÓN DE AGREGACIÓN SUM JUNTO CON LA CLÁUSULA HAVING PARA FILTRAR AQUELLOS CLIENTES CUYO TOTAL DE PAGOS ES MAYOR A 30.
*/
SELECT
	first_name,
	email
FROM
	customer
WHERE
	customer_id IN (SELECT
						customer_id
					FROM
						payment
					GROUP BY
						customer_id
					HAVING 
						SUM(amount) > 30)
/*
ESTE CÓDIGO SQL OBTIENE LOS NOMBRES Y CORREOS ELECTRÓNICOS DE LOS CLIENTES QUE VIVEN EN EL DISTRITO 'CALIFORNIA' Y CUYO MONTO TOTAL DE PAGOS SUPERA LOS 100. UTILIZA DOS
SUBCONSULTAS: UNA PARA FILTRAR CLIENTES SEGÚN SU DIRECCIÓN EN EL DISTRITO ESPECIFICADO, Y OTRA PARA IDENTIFICAR CLIENTES CUYO TOTAL DE PAGOS AGRUPADOS POR 'CUSTOMER_ID' ES
MAYOR A 100.
*/
SELECT
	first_name,
	email
FROM
	customer
WHERE
	address_id IN (SELECT
				       address_id
				   From
				       address
				   WHERE
				   	   district = 'California')
	AND customer_id IN (SELECT
					        customer_id
					    FROM
					        payment
					    GROUP BY
					        customer_id
					    HAVING 
							SUM(amount) > 100)