/*
ESTE CÓDIGO SQL CALCULA EL PROMEDIO DIARIO DE INGRESOS GENERADOS POR PAGOS, REDONDEADO A DOS DECIMALES. UTILIZA UNA SUBCONSULTA QUE AGRUPA LOS PAGOS POR FECHA Y SUMA LOS
MONTOS DE CADA DÍA, Y LUEGO APLICA LA FUNCIÓN AVG SOBRE ESOS RESULTADOS PARA OBTENER EL PROMEDIO GENERAL DE INGRESOS POR DÍA.
*/
SELECT
	ROUND(AVG(amount_per_day),2) AS daily_rev_avg
FROM
	(SELECT
	     SUM(amount) AS amount_per_day,
		 DATE(payment_date)
	 FROM
	     payment
	 GROUP BY
	 	 DATE(payment_date)) AS A