/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS DE LA TABLA 'PAYMENT' Y AGREGA UNA COLUMNA CALCULADA QUE REPRESENTA LA DIFERENCIA ENTRE EL MONTO MÁXIMO DE TODOS LOS PAGOS Y EL
MONTO DE CADA PAGO INDIVIDUAL. UTILIZA UNA SUBCONSULTA PARA OBTENER EL VALOR MÁXIMO DE LA COLUMNA 'AMOUNT' Y LO RESTA DE CADA VALOR DE PAGO.
*/
SELECT
	*,
	(SELECT
	     MAX(amount)
	 FROM
	 	 payment) - amount
FROM
	payment