/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS DE LA TABLA 'PAYMENT' CUYO MONTO ES IGUAL AL MONTO MÁXIMO PAGADO POR CADA CLIENTE. UTILIZA UNA SUBCONSULTA CORRELACIONADA QUE
COMPARA EL MONTO DE CADA PAGO CON EL MONTO MÁXIMO REALIZADO POR EL MISMO CLIENTE, IDENTIFICADO POR 'CUSTOMER_ID'.
*/
SELECT
	*
FROM
	payment AS p1
WHERE
	amount = (SELECT
				  MAX(amount)
			  FROM
				  payment AS p2
			  WHERE
				  p1.customer_id = p2.customer_id)
/*
ESTE CÓDIGO SQL RECUPERA EL TÍTULO, ID DE PELÍCULA, COSTO DE REEMPLAZO Y CLASIFICACIÓN DE LAS PELÍCULAS CUYO COSTO DE REEMPLAZO ES EL MÁS BAJO DENTRO DE SU MISMA
CLASIFICACIÓN ('RATING'). UTILIZA UNA SUBCONSULTA CORRELACIONADA PARA COMPARAR EL COSTO DE REEMPLAZO DE CADA PELÍCULA CON EL MÍNIMO COSTO DE REEMPLAZO ENTRE LAS PELÍCULAS
QUE COMPARTEN LA MISMA CLASIFICACIÓN.
*/
SELECT
	title,
	film_id,
	replacement_cost,
	rating
FROM
	film AS f1
WHERE
	replacement_cost = (SELECT
							MIN(replacement_cost)
						FROM
							film AS f2
						WHERE
							f1.rating = f2.rating)
/*
ESTE CÓDIGO SQL RECUPERA EL TÍTULO, ID, DURACIÓN Y CLASIFICACIÓN DE LAS PELÍCULAS CUYA DURACIÓN ES LA MÁS LARGA DENTRO DE SU MISMA CLASIFICACIÓN ('RATING'). UTILIZA UNA
SUBCONSULTA CORRELACIONADA PARA COMPARAR LA DURACIÓN DE CADA PELÍCULA CON LA MÁXIMA DURACIÓN ENTRE LAS PELÍCULAS QUE COMPARTEN LA MISMA CLASIFICACIÓN.
*/
SELECT
	title,
	film_id,
	length,
	rating
FROM
	film AS f1
WHERE
	length = (SELECT
				  MAX(length)
			  FROM
				  film AS f2
			  WHERE
				  f1.rating = f2.rating)