/*
ESTE CÓDIGO SQL RECUPERA INFORMACIÓN DETALLADA DE CADA PAGO, INCLUYENDO EL ID DEL PAGO, ID DEL CLIENTE, ID DEL PERSONAL Y MONTO PAGADO. ADEMÁS, AGREGA DOS COLUMNAS
CALCULADAS MEDIANTE SUBCONSULTAS CORRELACIONADAS: UNA CON LA SUMA TOTAL DE PAGOS REALIZADOS POR CADA CLIENTE Y OTRA CON EL NÚMERO TOTAL DE PAGOS QUE HA HECHO ESE MISMO
CLIENTE. LOS RESULTADOS SE ORDENAN POR ID DE CLIENTE Y MONTO DE PAGO EN ORDEN DESCENDENTE.
*/
SELECT
	payment_id,
	customer_id,
	staff_id,
	amount,
	(SELECT
		 SUM(amount) AS sum_amount
	 FROM
	 	 payment AS p2
	 WHERE 
	 	 p1.customer_id = p2.customer_id),
	 (SELECT
		 COUNT(amount) AS count_payments
	 FROM
	 	 payment AS p2
	 WHERE
	 	 p1.customer_id = p2.customer_id)
FROM
	payment AS p1
ORDER BY
	customer_id,
	amount DESC
/*
ESTE CÓDIGO SQL RECUPERA EL TÍTULO, COSTO DE REEMPLAZO Y CLASIFICACIÓN DE LAS PELÍCULAS CUYO COSTO DE REEMPLAZO ES EL MÁS ALTO DENTRO DE SU MISMA CLASIFICACIÓN ('RATING').
ADEMÁS, INCLUYE UNA COLUMNA CALCULADA QUE MUESTRA EL PROMEDIO DEL COSTO DE REEMPLAZO PARA TODAS LAS PELÍCULAS CON LA MISMA CLASIFICACIÓN. UTILIZA DOS SUBCONSULTAS
CORRELACIONADAS PARA COMPARAR Y CALCULAR ESTOS VALORES POR CATEGORÍA.
*/
SELECT
	title,
	replacement_cost,
	rating,
	(SELECT
		 AVG(replacement_cost)
	 FROM
	 	 film AS f2
	 WHERE 
		 f1.rating = f2.rating)
FROM
	film AS f1
WHERE
	replacement_cost = (SELECT
							MAX(replacement_cost)
						FROM
							film AS f3
						WHERE
							f1.rating = f3.rating)
/*
ESTE CÓDIGO SQL RECUPERA EL NOMBRE, MONTO Y ID DE PAGO DE LOS CLIENTES QUE HAN REALIZADO SU PAGO MÁS ALTO. REALIZA UNA UNIÓN INTERNA ENTRE LAS TABLAS 'CUSTOMER' Y
'PAYMENT', Y UTILIZA UNA SUBCONSULTA CORRELACIONADA PARA COMPARAR CADA MONTO CON EL MONTO MÁXIMO PAGADO POR EL MISMO CLIENTE, IDENTIFICADO POR 'CUSTOMER_ID'.
*/
SELECT
	first_name,
	amount,
	payment_id
FROM
	customer AS c1
INNER JOIN
	payment AS p1
ON
	c1.customer_id = p1.customer_id
WHERE
	amount = (SELECT
			       MAX(amount)
			   FROM
			   	   payment AS p2
			   WHERE
			   	   p1.customer_id = p2.customer_id)