/*
ESTE CÓDIGO SQL CREA UNA TABLA LLAMADA 'DIRECTOR' QUE ALMACENA INFORMACIÓN PERSONAL DE DIRECTORES, INCLUYENDO SU ID, NOMBRE DE CUENTA, NOMBRES, FECHA DE NACIMIENTO Y
DIRECCIÓN. EL CAMPO 'DIRECTOR_ID' ES LA CLAVE PRIMARIA Y SE GENERA AUTOMÁTICAMENTE. EL CAMPO 'DIRECTOR_ACCOUNT_NAME' ES ÚNICO PARA EVITAR DUPLICADOS. EL CAMPO 'LAST_NAME'
TIENE UN VALOR POR DEFECTO DE 'NOT SPECIFIED'. LA TABLA TAMBIÉN INCLUYE UNA CLAVE FORÁNEA HACIA LA TABLA 'ADDRESS' PARA RELACIONAR LA DIRECCIÓN DEL DIRECTOR.
*/
CREATE TABLE director
	(
	director_id SERIAL PRIMARY KEY,
	director_account_name VARCHAR(20) UNIQUE,
	first_name VARCHAR(50),
	last_name VARCHAR(50) DEFAULT 'Not specified',
	date_of_birth DATE,
	address_id INT REFERENCES address(address_id)
	)
/*
ESTE CÓDIGO SQL MODIFICA LA ESTRUCTURA DE LA TABLA 'DIRECTOR'. CAMBIA EL TIPO DE DATO DEL CAMPO 'DIRECTOR_ACCOUNT_NAME' A VARCHAR(30), ELIMINA EL VALOR POR DEFECTO DEL
CAMPO 'LAST_NAME' Y LO ESTABLECE COMO OBLIGATORIO (NOT NULL). ADEMÁS, AGREGA UNA NUEVA COLUMNA LLAMADA 'EMAIL' DE TIPO VARCHAR(40) PARA ALMACENAR LA DIRECCIÓN DE CORREO
ELECTRÓNICO DEL DIRECTOR.
*/
ALTER TABLE director
ALTER COLUMN director_account_name TYPE VARCHAR(30),
ALTER COLUMN last_name DROP DEFAULT,
ALTER COLUMN last_name SET NOT NULL,
ADD COLUMN email VARCHAR(40)
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS Y COLUMNAS DE LA TABLA 'DIRECTORS', MOSTRANDO LA INFORMACIÓN COMPLETA DE CADA DIRECTOR ALMACENADO EN DICHA TABLA.
*/
SELECT
	*
FROM
	directors
/*
ESTE CÓDIGO SQL RENOMBRA LA COLUMNA 'DIRECTOR_ACCOUNT_NAME' DE LA TABLA 'DIRECTOR' A 'ACCOUNT_NAME'.
*/
ALTER TABLE director
RENAME director_account_name TO account_name
/*
ESTE CÓDIGO SQL CAMBIA EL NOMBRE DE LA TABLA 'DIRECTOR' A 'DIRECTORS'
*/
ALTER TABLE director
RENAME TO directors