/*
ESTE CÓDIGO SQL CREA UNA TABLA LLAMADA 'EMP_TABLE' PARA ALMACENAR INFORMACIÓN DE EMPLEADOS. INCLUYE DOS CAMPOS: 'EMP_ID', QUE ES UNA CLAVE PRIMARIA GENERADA
AUTOMÁTICAMENTE, Y 'EMP_NAME', QUE ALMACENA EL NOMBRE DEL EMPLEADO EN FORMATO DE TEXTO.
*/
CREATE TABLE emp_table 
	(
	emp_id SERIAL PRIMARY KEY,
	emp_name TEXT
	)
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS Y COLUMNAS DE LA TABLA 'EMP_TABLE', MOSTRANDO LA INFORMACIÓN COMPLETA DE LOS EMPLEADOS ALMACENADOS EN DICHA TABLA.
*/
SELECT
	*
FROM
	emp_table
/*
ESTE CÓDIGO SQL ELIMINA COMPLETAMENTE LA TABLA 'EMP_TABLE' DE LA BASE DE DATOS, INCLUYENDO TODOS SUS DATOS Y ESTRUCTURA. ESTA ACCIÓN ES IRREVERSIBLE Y DEBE USARSE CON
PRECAUCIÓN.
*/
DROP TABLE emp_table
/*
ESTE CÓDIGO SQL INSERTA DOS REGISTROS EN LA TABLA 'EMP_TABLE'. AGREGA LOS DATOS DE DOS EMPLEADOS: UNO CON ID 1 Y NOMBRE 'FRANK', Y OTRO CON ID 2 Y NOMBRE 'MARIA'.
*/
INSERT INTO emp_table
VALUES
	(1,'Frank'),
	(2,'Maria')
/*
ESTE CÓDIGO SQL ELIMINA TODOS LOS REGISTROS DE LA TABLA 'EMP_TABLE' DE MANERA RÁPIDA Y EFICIENTE, SIN BORRAR LA ESTRUCTURA DE LA TABLA.
*/
TRUNCATE TABLE emp_table