/*
ESTE CÓDIGO SQL ACTUALIZA LA TABLA 'FILM', CAMBIANDO EL VALOR DE LA COLUMNA 'RENTAL_RATE' DE 0.99 A 1.99 EN TODOS LOS REGISTROS DONDE SE CUMPLA ESA CONDICIÓN. ESTA
MODIFICACIÓN PUEDE REFLEJAR UN AJUSTE DE PRECIOS EN LAS TARIFAS DE ALQUILER DE PELÍCULAS.
*/
UPDATE film
SET rental_rate = 1.99
WHERE
	rental_rate = 0.99
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS Y COLUMNAS DE LA TABLA 'FILM', MOSTRANDO LA INFORMACIÓN COMPLETA DE CADA PELÍCULA ALMACENADA EN DICHA TABLA.
*/
SELECT
	*
FROM
	film
/*
ESTE CÓDIGO SQL AGREGA UNA NUEVA COLUMNA LLAMADA 'INITIALS' A LA TABLA 'CUSTOMER'. ESTA COLUMNA ES DE TIPO VARCHAR(4) Y ESTÁ DESTINADA A ALMACENAR LAS INICIALES DEL
CLIENTE.
*/
ALTER TABLE customer
ADD COLUMN initials VARCHAR(4)
/*
ESTE CÓDIGO SQL ACTUALIZA LA COLUMNA 'INITIALS' DE LA TABLA 'CUSTOMER', ASIGNANDO LAS INICIALES DE CADA CLIENTE. PARA ELLO, TOMA LA PRIMERA LETRA DEL NOMBRE ('FIRST_NAME')
Y LA PRIMERA LETRA DEL APELLIDO ('LAST_NAME'), UNIÉNDOLAS CON PUNTOS INTERMEDIOS EN EL FORMATO 'F.L.'.
*/
UPDATE customer
SET initials = LEFT(first_name,1) || '.' || LEFT(last_name,1) || '.'
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS Y COLUMNAS DE LA TABLA 'CUSTOMER', MOSTRANDO LA INFORMACIÓN COMPLETA DE CADA CLIENTE ALMACENADO EN DICHA TABLA.
*/
SELECT
	*
FROM
	customer