/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS CAMPOS DE LA TABLA 'PAYMENT' PARA LOS REGISTROS CUYO 'PAYMENT_ID' SEA IGUAL A 17064 O 17067. ESTA CONSULTA PERMITE OBTENER DETALLES
ESPECÍFICOS DE TRANSACCIONES PARTICULARES.
*/
SELECT
	*
FROM
	payment
WHERE
	payment_id IN (17064,17067)
/*
ESTE CÓDIGO SQL ELIMINA LOS REGISTROS DE LA TABLA 'PAYMENT' CUYO 'PAYMENT_ID' SEA IGUAL A 17064 O 17067. ADEMÁS, UTILIZA LA CLÁUSULA 'RETURNING *' PARA DEVOLVER LOS DATOS
DE LOS REGISTROS ELIMINADOS, PERMITIENDO VERIFICAR QUÉ INFORMACIÓN FUE BORRADA.
*/
DELETE FROM payment
WHERE
	payment_id IN (17064,17067)
RETURNING
	*