/*
ESTE CÓDIGO SQL CREA UNA NUEVA TABLA LLAMADA 'CUSTOMER_SPENDINGS' BASADA EN UNA CONSULTA QUE UNE LAS TABLAS 'CUSTOMER' Y 'PAYMENT'. LA TABLA RESULTANTE CONTIENE DOS
COLUMNAS: EL NOMBRE COMPLETO DEL CLIENTE (COMBINANDO 'FIRST_NAME' Y 'LAST_NAME') Y EL MONTO TOTAL DE LOS PAGOS REALIZADOS POR CADA CLIENTE. LOS DATOS SE AGRUPAN POR NOMBRE
COMPLETO PARA CALCULAR LA SUMA DE LOS PAGOS.
*/
CREATE TABLE customer_spendings
AS SELECT
	   first_name || ' ' || last_name AS name,
	   SUM(amount) AS total_amount
   FROM
	   customer
   LEFT OUTER JOIN
	   payment
   ON
	   customer.customer_id = payment.customer_id
   GROUP BY
	   first_name || ' ' || last_name
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS Y COLUMNAS DE LA TABLA 'CUSTOMER_SPENDINGS', MOSTRANDO EL NOMBRE COMPLETO DE CADA CLIENTE JUNTO CON EL MONTO TOTAL QUE HA
PAGADO SEGÚN LOS DATOS ALMACENADOS EN LA TABLA.
*/
SELECT
	*
FROM
	customer_spendings