/*
ESTE CÓDIGO SQL RECUPERA INFORMACIÓN DE PELÍCULAS, INCLUYENDO SU ID, TÍTULO, CATEGORÍA, DURACIÓN Y EL PROMEDIO DE DURACIÓN DE PELÍCULAS POR CATEGORÍA. UTILIZA UNIONES
IZQUIERDAS ENTRE LAS TABLAS DE PELÍCULAS, CATEGORÍAS DE PELÍCULAS Y CATEGORÍAS. LA FUNCIÓN DE VENTANA 'AVG() OVER(PARTITION BY category)' PERMITE CALCULAR EL PROMEDIO DE
DURACIÓN AGRUPADO POR CATEGORÍA. LOS RESULTADOS SE ORDENAN POR EL ID DE LA PELÍCULA EN ORDEN ASCENDENTE.
*/
SELECT
	film.film_id,
	title,
	name AS category,
	length AS length_of_movie,
	ROUND(AVG(length) OVER(PARTITION BY category),2) AS avg_length_in_category
FROM
	film
LEFT OUTER JOIN
	film_category
ON
	film.film_id = film_category.film_id
LEFT OUTER JOIN
	category
ON
	film_category.category_id = category.category_id
ORDER BY
	film_id ASC
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS CAMPOS DE LA TABLA 'payment' Y AGREGA UNA COLUMNA ADICIONAL QUE MUESTRA LA CANTIDAD DE VECES QUE SE REPITE UNA COMBINACIÓN ESPECÍFICA
DE 'amount' Y 'customer_id'. UTILIZA LA FUNCIÓN DE VENTANA 'COUNT(*) OVER(PARTITION BY amount, customer_id)' PARA CONTAR OCURRENCIAS SIN AGRUPAR LOS RESULTADOS. LOS DATOS
SE ORDENAN POR EL ID DEL CLIENTE.
*/
SELECT
	*,
	COUNT(*) OVER(PARTITION BY amount,customer_id)
FROM
	payment
ORDER BY
	customer_id