/*
ESTE CÓDIGO SQL OBTIENE EL ID DEL VUELO, EL AEROPUERTO DE SALIDA Y LA SUMA ACUMULADA DE LA DIFERENCIA ENTRE LA HORA REAL DE LLEGADA Y LA HORA PROGRAMADA DE LLEGADA PARA
CADA VUELO. UTILIZA LA FUNCIÓN DE VENTANA 'SUM() OVER(ORDER BY flight_id)' PARA CALCULAR LA SUMA ACUMULATIVA ORDENADA POR EL ID DEL VUELO, LO QUE PERMITE ANALIZAR RETRASOS
O ADELANTOS EN LA LLEGADA DE LOS VUELOS A LO LARGO DEL TIEMPO.
*/
SELECT
	flight_id,
	departure_airport,
	SUM(actual_arrival-scheduled_arrival) OVER(ORDER BY flight_id)
FROM
	flights
/*
ESTE CÓDIGO SQL RECUPERA EL ID DEL VUELO, EL AEROPUERTO DE SALIDA Y LA SUMA ACUMULADA DE LA DIFERENCIA ENTRE LA HORA REAL Y LA HORA PROGRAMADA DE LLEGADA, AGRUPADA POR
AEROPUERTO DE SALIDA. UTILIZA LA FUNCIÓN DE VENTANA 'SUM() OVER(PARTITION BY departure_airport ORDER BY flight_id)' PARA CALCULAR LA SUMA ACUMULATIVA DE RETRASOS O ADELANTOS
POR AEROPUERTO, ORDENADA POR EL ID DEL VUELO.
*/
SELECT
	flight_id,
	departure_airport,
	SUM(actual_arrival-scheduled_arrival) OVER(PARTITION BY departure_airport ORDER BY flight_id)
FROM
	flights