/*
ESTE CÓDIGO SQL RECUPERA LOS CLIENTES CON MAYOR CANTIDAD DE PAGOS POR PAÍS, MOSTRANDO SOLO LOS TRES PRIMEROS DE CADA UNO. UTILIZA UNA SUBCONSULTA QUE UNE LAS TABLAS
'customer_list' Y 'payment', AGRUPA POR NOMBRE Y PAÍS, Y APLICA LA FUNCIÓN DE VENTANA 'RANK()' PARA ASIGNAR UNA POSICIÓN A CADA CLIENTE DENTRO DE SU PAÍS SEGÚN LA CANTIDAD
DE PAGOS. LA CONSULTA EXTERNA FILTRA LOS RESULTADOS PARA MOSTRAR SOLO AQUELLOS CON UN RANGO MENOR A 4.
*/
SELECT
	*
FROM
	(SELECT
		name,
		country,
		COUNT(*),
		RANK() OVER(PARTITION BY country ORDER BY COUNT(*) DESC) AS RANK
	FROM
		customer_list
	LEFT OUTER JOIN
		payment
	ON
		id=customer_id
	GROUP BY
		name,
		country)
WHERE
	RANK < 4