/*
ESTE CÓDIGO SQL REALIZA UN ANÁLISIS DIARIO DE LOS PAGOS REGISTRADOS, MOSTRANDO LA SUMA TOTAL POR DÍA, EL MONTO DEL DÍA ANTERIOR, LA DIFERENCIA ENTRE AMBOS Y EL PORCENTAJE DE
CRECIMIENTO. UTILIZA FUNCIONES DE VENTANA COMO 'LAG()' PARA OBTENER EL VALOR DEL DÍA PREVIO Y REALIZA CÁLCULOS ARITMÉTICOS PARA DETERMINAR LA VARIACIÓN ABSOLUTA Y PORCENTUAL
ENTRE DÍAS. LOS DATOS SE AGRUPAN POR FECHA DE PAGO.
*/
SELECT
	SUM(amount),
	DATE(payment_date),
	LAG(SUM(amount)) OVER(ORDER BY DATE(payment_date)) AS previous_day,
	SUM(amount) - LAG(SUM(amount)) OVER(ORDER BY DATE(payment_date)) AS difference,
	ROUND((SUM(amount) - LAG(SUM(amount)) OVER(ORDER BY DATE(payment_date))) / LAG(SUM(amount)) OVER(ORDER BY DATE(payment_date)) * 100,2) AS percentage_growth
FROM
	payment
GROUP BY
	DATE(payment_date)