/*
ESTE CÓDIGO SQL RECUPERA LA SUMA DE PAGOS REALIZADOS POR CLIENTES, AGRUPANDO LOS RESULTADOS MEDIANTE 'GROUPING SETS'. SE GENERAN DOS AGRUPACIONES: UNA POR NOMBRE Y APELLIDO
DEL CLIENTE, Y OTRA QUE INCLUYE TAMBIÉN EL ID DEL PERSONAL QUE PROCESÓ EL PAGO. ESTO PERMITE OBTENER TANTO TOTALES POR CLIENTE COMO POR CLIENTE Y EMPLEADO. LA CONSULTA
UTILIZA UNA UNIÓN IZQUIERDA ENTRE LAS TABLAS 'customer' Y 'payment', Y ORDENA LOS RESULTADOS POR NOMBRE.
*/
SELECT
	first_name,
	last_name,
	staff_id,
	SUM(amount)
FROM
	customer
LEFT OUTER JOIN
	payment
ON
	customer.customer_id = payment.customer_id
GROUP BY
	GROUPING SETS(
		(first_name,last_name),
		(first_name,last_name,staff_id)
	)
ORDER BY first_name ASC