/*
ESTE CÓDIGO SQL RECUPERA LA SUMA TOTAL DE PAGOS REALIZADOS POR CLIENTES Y CALCULA EL PORCENTAJE QUE REPRESENTA CADA TOTAL RESPECTO AL MAYOR MONTO REGISTRADO PARA ESE CLIENTE
. UTILIZA 'GROUPING SETS' PARA AGRUPAR POR NOMBRE Y APELLIDO DEL CLIENTE, Y TAMBIÉN POR CLIENTE Y EMPLEADO. LA FUNCIÓN DE VENTANA 'FIRST_VALUE()' OBTIENE EL MAYOR MONTO DE
PAGO POR CLIENTE, ORDENADO DE FORMA DESCENDENTE, Y SE USA PARA CALCULAR EL PORCENTAJE RELATIVO DE CADA AGRUPACIÓN. LOS RESULTADOS SE ORDENAN POR NOMBRE DEL CLIENTE.
*/
SELECT
	first_name,
	last_name,
	staff_id,
	SUM(amount) AS total,
	ROUND(FIRST_VALUE(SUM(amount)) OVER(PARTITION BY first_name,last_name ORDER BY SUM(amount) DESC) / SUM(amount) * 100,2) AS percentage
FROM
	customer
LEFT OUTER JOIN
	payment
ON
	customer.customer_id = payment.customer_id
GROUP BY
	GROUPING SETS(
		(first_name,last_name),
		(first_name,last_name,staff_id)
	)
ORDER BY first_name ASC