/*
ESTE CÓDIGO SQL REALIZA UN ANÁLISIS DE LOS MONTOS DE RESERVA AGRUPADOS JERÁRQUICAMENTE POR TRIMESTRE, MES, SEMANA DENTRO DEL MES Y DÍA. UTILIZA LA FUNCIÓN 'ROLLUP' PARA
GENERAR TOTALES ACUMULADOS EN CADA NIVEL DE AGRUPACIÓN, PERMITIENDO VER DESDE EL TOTAL GENERAL HASTA LOS DETALLES DIARIOS. SE EXTRAEN EL TRIMESTRE Y EL MES DE LA FECHA DE
RESERVA, SE OBTIENE LA SEMANA CON 'TO_CHAR(..., 'W')', Y SE SUMAN LOS MONTOS DE RESERVA. LOS RESULTADOS SE ORDENAN POR TRIMESTRE, MES, SEMANA Y DÍA.
*/
SELECT
	EXTRACT(QUARTER FROM book_date) AS quarter,
	EXTRACT(MONTH FROM book_date) AS month,
	TO_CHAR(book_date, 'W') AS week_in_month,
	DATE(book_date) AS day,
	SUM(total_amount) AS booking_amount
FROM
	bookings
GROUP BY
	ROLLUP(
		EXTRACT(QUARTER FROM book_date),
		EXTRACT(MONTH FROM book_date),
		TO_CHAR(book_date, 'W'),
		DATE(book_date)
	)
ORDER BY
	quarter,
	month,
	week_in_month,
	day