/*
ESTE CÓDIGO SQL COMPARA PELÍCULAS QUE TIENEN LA MISMA DURACIÓN PERO DIFERENTE TÍTULO. REALIZA UNA AUTO-UNIÓN IZQUIERDA DE LA TABLA 'film', COMPARANDO CADA PELÍCULA (f1) CON
OTRA (f2) QUE TENGA IGUAL DURACIÓN PERO DISTINTO TÍTULO. EL RESULTADO MUESTRA EL TÍTULO DE AMBAS PELÍCULAS Y LA DURACIÓN COMPARTIDA, ORDENADO DE FORMA DESCENDENTE POR LA
DURACIÓN.
*/
SELECT
	f1.title,
	f2.title,
	f2.length
FROM
	film AS f1
LEFT OUTER JOIN
	film AS f2
ON
	f1.length = f2.length
WHERE
	f1.title <> f2.title
ORDER BY
	f2.length DESC