/*
ESTE CÓDIGO SQL CREA O REEMPLAZA UNA FUNCIÓN LLAMADA `NAME_SEARCH` QUE RECIBE COMO PARÁMETROS EL NOMBRE Y APELLIDO DE UN CLIENTE. LA FUNCIÓN DEVUELVE EL TOTAL DE PAGOS
REALIZADOS POR ESE CLIENTE, SUMANDO LOS MONTOS DE LA TABLA `PAYMENT` RELACIONADA CON LA TABLA `CUSTOMER` MEDIANTE UNA UNIÓN NATURAL IZQUIERDA. ESTÁ ESCRITA EN LENGUAJE
PLPGSQL Y RETORNA UN VALOR DECIMAL CON DOS DECIMALES DE PRECISIÓN.
*/
CREATE OR REPLACE FUNCTION name_search (f_name VARCHAR(20),l_name VARCHAR(20))
	RETURNS DECIMAL(6,2)
	LANGUAGE plpgsql
	AS
		$$
		DECLARE
			total DECIMAL(6,2);
		BEGIN
			SELECT
				SUM(amount)
			INTO
				total
			FROM
				payment
			NATURAL LEFT JOIN
				customer
			WHERE
				(first_name = f_name)
				AND (last_name = l_name);
			RETURN
				total;
	END;
		$$
/*
ESTE CÓDIGO SQL EJECUTA LA FUNCIÓN `NAME_SEARCH` PASÁNDOLE COMO PARÁMETROS EL NOMBRE 'AMY' Y EL APELLIDO 'LOPEZ'. EL RESULTADO DEVUELTO ES EL TOTAL DE PAGOS REALIZADOS POR
ESE CLIENTE, SUMANDO LOS MONTOS DE LA TABLA `PAYMENT` RELACIONADA CON LA TABLA `CUSTOMER`.
*/
SELECT
	name_search('AMY','LOPEZ')
/*
ESTE CÓDIGO SQL RECORRE TODOS LOS CLIENTES EN LA TABLA `CUSTOMER` Y EJECUTA LA FUNCIÓN `NAME_SEARCH` PARA CADA UNO DE ELLOS, PASANDO SU NOMBRE Y APELLIDO COMO PARÁMETROS.
EL RESULTADO MUESTRA EL NOMBRE, APELLIDO Y EL TOTAL DE PAGOS REALIZADOS POR CADA CLIENTE SEGÚN LA SUMA DE MONTOS EN LA TABLA `PAYMENT`.
*/
SELECT
	first_name,
	last_name,
	name_search(first_name,last_name)
FROM
	customer