/*
ESTE CÓDIGO SQL CREA UNA TABLA LLAMADA `ACC_BALANCE` QUE ALMACENA INFORMACIÓN DE SALDOS DE CUENTAS. LA TABLA INCLUYE UN IDENTIFICADOR ÚNICO AUTOMÁTICO (`ID`), EL NOMBRE Y
APELLIDO DEL TITULAR DE LA CUENTA, Y EL MONTO ASOCIADO A LA CUENTA. TODOS LOS CAMPOS SON OBLIGATORIOS Y EL CAMPO `ID` ES LA CLAVE PRIMARIA.
*/
CREATE TABLE acc_balance(
    id SERIAL PRIMARY KEY,
    first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
    amount DEC(9,2) NOT NULL    
)
/*
ESTE CÓDIGO SQL INSERTA DOS REGISTROS EN LA TABLA `ACC_BALANCE`, CADA UNO CON UN IDENTIFICADOR, NOMBRE, APELLIDO Y MONTO ASOCIADO A LA CUENTA. LOS DATOS CORRESPONDEN A LOS
CLIENTES 'TIM BROWN' CON UN SALDO DE 2500 Y 'SANDRA MILLER' CON UN SALDO DE 1600.
*/
INSERT INTO acc_balance
VALUES 
	(1,'Tim','Brown',2500),
	(2,'Sandra','Miller',1600)
/*
ESTE CÓDIGO SQL RECUPERA TODOS LOS REGISTROS DE LA TABLA `ACC_BALANCE`, MOSTRANDO EL IDENTIFICADOR, NOMBRE, APELLIDO Y MONTO ASOCIADO A CADA CUENTA. ES ÚTIL PARA VER EL
CONTENIDO COMPLETO DE LA TABLA Y VALIDAR LOS DATOS INSERTADOS.
*/
SELECT
	*
FROM
	acc_balance
/*
ESTE COMANDO INICIA UNA TRANSACCIÓN EN SQL. A PARTIR DE ESTE MOMENTO, TODAS LAS OPERACIONES QUE SE EJECUTEN ESTARÁN DENTRO DE LA MISMA TRANSACCIÓN HASTA QUE SE EJECUTE UN
`COMMIT` PARA GUARDAR LOS CAMBIOS PERMANENTEMENTE O UN `ROLLBACK` PARA DESHACERLOS.
*/
BEGIN;
/*
ESTE CÓDIGO SQL ACTUALIZA EL TÍTULO DE PUESTO DEL EMPLEADO CON IDENTIFICADOR 2 A 'HEAD OF SALES' EN LA TABLA `EMPLOYEES`.
*/
UPDATE employees
SET position_title = 'Head of Sales'
WHERE
	emp_id = 2;
/*
ESTE CÓDIGO SQL ACTUALIZA EL SALARIO DEL EMPLEADO CON IDENTIFICADOR 2 A \$12,587.00 EN LA TABLA `EMPLOYEES`.
*/
UPDATE employees
SET salary = 12587.00
WHERE
	emp_id = 2;
/*
ESTE CÓDIGO SQL ACTUALIZA EL TÍTULO DE PUESTO DEL EMPLEADO CON IDENTIFICADOR 3 A 'HEAD OF BI' EN LA TABLA `EMPLOYEES`.
*/
UPDATE employees
SET position_title = 'Head of BI'
WHERE
	emp_id = 3;
/*
ESTE CÓDIGO SQL ACTUALIZA EL SALARIO DEL EMPLEADO CON IDENTIFICADOR 3 A \$14,614.00 EN LA TABLA `EMPLOYEES`.
*/
UPDATE employees
SET salary = 14614.00
WHERE
	emp_id = 3;
/*
ESTE COMANDO FINALIZA LA TRANSACCIÓN INICIADA PREVIAMENTE Y CONFIRMA TODOS LOS CAMBIOS REALIZADOS EN LA BASE DE DATOS, HACIÉNDOLOS PERMANENTES.
*/
COMMIT;