/*
ESTA CONSULTA DEFINE UNA CTE (EXPRESIÓN DE TABLA COMÚN) LLAMADA 'CUSTOMER_TOTALS' QUE CALCULA, PARA CADA CLIENTE, EL NÚMERO TOTAL DE RENTAS REALIZADAS Y EL MONTO TOTAL
PAGADO. PARA ELLO, SE REALIZAN UNIONES ENTRE LAS TABLAS 'CUSTOMER', 'RENTAL' Y 'PAYMENT', AGRUPANDO LOS RESULTADOS POR ID DE CLIENTE, NOMBRE Y APELLIDO. ESTA CTE PUEDE SER
UTILIZADA POSTERIORMENTE EN UNA CONSULTA PRINCIPAL PARA FILTRAR, ORDENAR O ANALIZAR LOS DATOS AGREGADOS DE CLIENTES.
*/
WITH customer_totals AS(
	SELECT
		customer.customer_id,
		first_name,
		last_name,
		COUNT(rental.rental_id) AS rental_count,
		SUM(amount) AS total_amount
	FROM
		customer
	JOIN
		rental
	ON
		customer.customer_id = rental.customer_id
	JOIN
		payment
	ON
		rental.rental_id = payment.rental_id
	GROUP BY
		customer.customer_id,
		first_name,
		last_name
)
/*
ESTA CONSULTA SQL RECUPERA LOS DATOS DE CLIENTES DESDE LA CTE 'CUSTOMER_TOTALS' CUYO NÚMERO DE RENTAS ('RENTAL_COUNT') ES MAYOR AL PROMEDIO GENERAL DE RENTAS REALIZADAS
POR TODOS LOS CLIENTES. UTILIZA UNA SUBCONSULTA PARA CALCULAR EL PROMEDIO DE RENTAS Y FILTRA LOS RESULTADOS MOSTRANDO SOLO AQUELLOS CLIENTES QUE SUPERAN EL VALOR PROMEDIO.
*/
SELECT
	customer_id,
	first_name,
	last_name,
	rental_count,
	total_amount
FROM
	customer_totals
WHERE
	rental_count > (SELECT
						AVG(rental_count)
					FROM
						customer_totals)