/*
ESTE CÓDIGO SQL DEFINE UNA CTE RECURSIVA LLAMADA 'SUBORDINATE_TREE' QUE CONSTRUYE UN ÁRBOL JERÁRQUICO DE SUBORDINADOS A PARTIR DE UN EMPLEADO ESPECÍFICO (EN ESTE CASO, EL
EMPLEADO CON ID 1). LA CONSULTA INICIAL SELECCIONA AL EMPLEADO RAÍZ, Y LA PARTE RECURSIVA AGREGA SUS SUBORDINADOS DIRECTOS E INDIRECTOS, INCREMENTANDO EL NIVEL DE
JERARQUÍA EN CADA ITERACIÓN.
*/
WITH RECURSIVE subordinate_tree AS(
	SELECT
		employee.employee_id,
		name,
		manager_id,
		1 AS level
	FROM
		employee
	WHERE
		employee_id = 1
    UNION ALL
	SELECT
		employee.employee_id,
		employee.name,
		employee.manager_id,
		level + 1 AS level
    FROM
		employee
    INNER JOIN
		subordinate_tree
	ON
		employee.manager_id = subordinate_tree.employee_id
)
/*
ESTE CÓDIGO SQL REALIZA UNA CONSULTA FINAL SOBRE LA CTE RECURSIVA 'SUBORDINATE_TREE' PARA MOSTRAR LA LISTA DE EMPLEADOS QUE SON SUBORDINADOS DEL EMPLEADO CON ID 1.
INCLUYE EL ID DEL EMPLEADO, SU NOMBRE, EL ID DE SU JEFE DIRECTO Y EL NIVEL DE JERARQUÍA DENTRO DE LA ESTRUCTURA ORGANIZACIONAL.
*/
SELECT
	employee_id,
	name,
	manager_id,
	level
FROM
	subordinate_tree